// Tanzania Regions and Locations (mainland only, excluding Zanzibar)

export const REGIONS_WITH_LOCATIONS: Record<string, string[]> = {
  "Dar es Salaam": [
    "CBD (City Centre)",
    "Mikocheni",
    "Msasani",
    "Kariakoo",
    "Kinondoni",
    "Ilala",
    "Temeke",
    "Mbagala",
    "Mbezi Beach",
    "Tegeta",
    "Kijitonyama",
    "Sinza",
    "Mwenge",
    "Masaki",
    "Oyster Bay",
    "Julius Nyerere International Airport (JNIA)",
    "Dar es Salaam Port",
    "Ubungo",
    "Gongo la Mboto",
    "Kimara",
  ],
  "Arusha": [
    "Arusha Town Centre",
    "Arusha Airport",
    "Kilimanjaro International Airport (KIA)",
    "Njiro",
    "Sakina",
    "Kijenge",
    "Themi",
    "Ngarenaro",
  ],
  "Kilimanjaro": [
    "Moshi Town",
    "Kilimanjaro International Airport (KIA)",
    "Himo",
    "Same",
    "Mwanga",
    "Kibosho",
  ],
  "Dodoma": [
    "Dodoma City Centre",
    "Dodoma Airport",
    "Makole",
    "Chamwino",
    "Kikuyu",
  ],
  "Mwanza": [
    "Mwanza City Centre",
    "Mwanza Airport",
    "Nyamagana",
    "Ilemela",
    "Capri Point",
    "Bugando",
  ],
  "Morogoro": [
    "Morogoro Town",
    "Mikumi",
    "Kilosa",
    "Mvomero",
    "Gairo",
  ],
  "Tanga": [
    "Tanga Town",
    "Tanga Airport",
    "Muheza",
    "Korogwe",
    "Lushoto",
    "Pangani",
  ],
  "Mbeya": [
    "Mbeya City Centre",
    "Mbeya Airport",
    "Tukuyu",
    "Kyela",
    "Rungwe",
  ],
  "Kagera": [
    "Bukoba Town",
    "Bukoba Airport",
    "Muleba",
    "Biharamulo",
    "Karagwe",
  ],
  "Iringa": [
    "Iringa Town",
    "Mafinga",
    "Ruaha National Park",
    "Kilolo",
  ],
  "Lindi": [
    "Lindi Town",
    "Kilwa",
    "Nachingwea",
    "Liwale",
  ],
  "Mtwara": [
    "Mtwara Town",
    "Mtwara Airport",
    "Masasi",
    "Newala",
    "Tandahimba",
  ],
  "Pwani": [
    "Kibaha",
    "Bagamoyo",
    "Mafia Island",
    "Kisarawe",
    "Mkuranga",
  ],
  "Geita": [
    "Geita Town",
    "Geita Gold Mine",
    "Chato",
  ],
  "Katavi": [
    "Mpanda Town",
    "Katavi National Park",
    "Mlele",
  ],
  "Kigoma": [
    "Kigoma Town",
    "Kigoma Airport",
    "Kasulu",
    "Kibondo",
    "Ujiji",
  ],
  "Manyara": [
    "Babati Town",
    "Lake Manyara",
    "Ngorongoro",
    "Hanang",
    "Mbulu",
  ],
  "Mara": [
    "Musoma Town",
    "Musoma Airport",
    "Bunda",
    "Serengeti",
    "Tarime",
  ],
  "Njombe": [
    "Njombe Town",
    "Makete",
    "Wanging'ombe",
  ],
  "Rukwa": [
    "Sumbawanga Town",
    "Kalambo",
    "Nkasi",
  ],
  "Ruvuma": [
    "Songea Town",
    "Songea Airport",
    "Tunduru",
    "Namtumbo",
  ],
  "Shinyanga": [
    "Shinyanga Town",
    "Kahama",
    "Kishapu",
    "Williamson Diamond Mine",
  ],
  "Simiyu": [
    "Bariadi Town",
    "Busega",
    "Itilima",
    "Maswa",
  ],
  "Singida": [
    "Singida Town",
    "Manyoni",
    "Ikungi",
  ],
  "Songwe": [
    "Songwe Town",
    "Songwe Airport",
    "Vwawa",
    "Mbozi",
  ],
  "Tabora": [
    "Tabora Town",
    "Tabora Airport",
    "Urambo",
    "Sikonge",
  ],
};

export const REGIONS = Object.keys(REGIONS_WITH_LOCATIONS).sort();

export const getLocations = (region: string): string[] => {
  const locations = REGIONS_WITH_LOCATIONS[region] || [];
  return [...locations, "Other (specify below)"];
};
